server:
  port: 8083 # C?ng m?c ??nh cho Booking Service [cite: 190]

spring:
  application:
    name: booking-service

  # C?u h�nh MariaDB (booking_db)
  datasource:
    url: jdbc:mariadb://localhost:3306/booking_db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # C?u h�nh RabbitMQ (Broker) [cite: 137, 192]
  rabbitmq:
    host: 172.20.35.147
    port: 5672
    username: guest
    password: guest
    # --- THÊM PHẦN BONUS RETRY VÀO ĐÂY ---
    listener:
      simple:
        retry:
          enabled: true # Bật tính năng thử lại
          initial-interval: 2000ms # Lần thử đầu cách 2 giây
          max-attempts: 3 # Thử tối đa 3 lần
          max-interval: 10000ms # Tối đa cách nhau 10s
management:
  endpoints:
    web:
      exposure:
        include: "*" # Phải có dòng này thì Dashboard mới đọc được dữ liệu
  endpoint:
    health:
      show-details: always
eureka:
  instance:
    health-check-url-path: /actuator/health
    hostname: 172.20.34.136       # Ép đè luôn cái tên mshome.net
    ip-address: 172.20.34.136     # Khai báo IP thật
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port} # Hiện cho đẹp trên Eureka
  client:
    service-url:
      defaultZone: http://172.20.35.147:8761/eureka/